// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Contexts;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240529134325_Migration11")]
    partial class Migration11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Talisay City",
                            FullName = "Pia Admin"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Cebu City",
                            FullName = "User Admin"
                        });
                });

            modelBuilder.Entity("Project.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("OrdersId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Project.Models.Orders", b =>
                {
                    b.Property<int>("OrdersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdersId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("OrdersId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Joyce Ice Cream",
                            Name = "Ice Cream",
                            Price = 10.0,
                            RestaurantId = 1,
                            Stock = 999
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Masarap",
                            Name = "Lollipop",
                            Price = 2.0,
                            RestaurantId = 1,
                            Stock = 500
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Lasagna",
                            Name = "Spaghetti",
                            Price = 10.0,
                            RestaurantId = 2,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "jollibee, Mcdo and kfc",
                            Name = "Chiken",
                            Price = 140.0,
                            RestaurantId = 2,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "yum, big mac, 4 cheese woper",
                            Name = "Burger",
                            Price = 150.0,
                            RestaurantId = 3,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "white, dark and milk",
                            Name = "chocolate",
                            Price = 100.0,
                            RestaurantId = 3,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "bla bla bla",
                            Name = "ambot",
                            Price = 100.0,
                            RestaurantId = 4,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "white, dark and milk",
                            Name = "chocolate",
                            Price = 100.0,
                            RestaurantId = 4,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "bla bla abla",
                            Name = "ambot",
                            Price = 100.0,
                            RestaurantId = 5,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "white, dark and milk",
                            Name = "chocolate",
                            Price = 100.0,
                            RestaurantId = 5,
                            Stock = 200
                        });
                });

            modelBuilder.Entity("Project.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Project.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locaton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Description = "The Pig & Palm offers a contemporary dining experience with a focus on European and gastropub cuisine. Founded by Michelin-starred British chef Jason Atherton and his Cebuana wife Irha, the restaurant features a modern, stylish interior with a relaxed atmosphere. The menu emphasizes locally sourced ingredients and innovative dishes, making it a popular spot for both brunch and dinner. Signature dishes include their creative takes on classic pub fare and a variety of cocktails crafted to perfection.",
                            Locaton = "MSY Tower, Pescadores Road, Cebu Business Park, Cebu City",
                            Name = "The Pig & Palm"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Description = "This family-owned restaurant offers a mix of Spanish and American dishes in a cozy, homey setting. The most popular dish is their Baby Back Ribs, which are renowned for their generous portions and delicious flavor​",
                            Locaton = "Cebu Business Park in Cebu City, Philippines",
                            Name = "Casa Verde"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Description = "House of Lechon specializes in the iconic Cebuano lechon, a traditional roasted pig known for its crispy skin and savory meat. The restaurant brings the renowned flavor of Carcar's lechon to the city, offering a taste of this beloved regional delicacy without the need for a long drive. The dining experience is enhanced by a casual, family-friendly atmosphere, perfect for enjoying authentic Filipino cuisine.",
                            Locaton = "General Maxilom Avenue corner Sergio Osmeña Boulevard, Brgy. Tejero, Cebu City, Philippines ",
                            Name = "House of Lechon"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Description = "Located in a beautifully restored colonial home, Circa 1900 combines historical charm with modern culinary excellence. The restaurant's ambiance is both vintage and sophisticated, providing a unique setting for dining. The menu features international dishes with a focus on local ingredients, skillfully prepared by their talented chefs. This makes Circa 1900 an ideal venue for intimate dinners and special occasions.",
                            Locaton = "Sanjercas Ville Ext. Rd, Cebu City​",
                            Name = "Circa 1900"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Description = "Vikings Luxury Buffet offers an extensive and lavish dining experience with a wide variety of dishes from different cuisines around the world. The buffet features stations for Filipino, Korean, Japanese, Greek, Italian, French, and Western food, along with dedicated dessert and drink sections. The spacious and modern interior can accommodate large groups, making it a popular choice for celebrations and gatherings.",
                            Locaton = "SM City Cebu, North Reclamation Area, Cebu City",
                            Name = "Vikings Luxury Buffet"
                        });
                });

            modelBuilder.Entity("Project.Models.Order", b =>
                {
                    b.HasOne("Project.Models.Orders", null)
                        .WithMany("OrdersList")
                        .HasForeignKey("OrdersId");
                });

            modelBuilder.Entity("Project.Models.Orders", b =>
                {
                    b.Navigation("OrdersList");
                });
#pragma warning restore 612, 618
        }
    }
}
